version: '2'
services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8000:80'
      - '443:443'
    # volumes:
    #   - /path/to/certs/:/var/lib/https-portal/
    links:
      - web
    restart: always
    environment:
      DOMAINS:
        'localhost -> http://web:${APP_PORT}'
        # '${APP_DOMAIN} -> http://web:${APP_PORT}'
      STAGE: 'local'
      # STAGE: 'production'

  web:
    image: nginx:stable-alpine
    container_name: node-app-nginx
    ports:
      - "${APP_PORT}:${PORT_INTERNAL}"
    volumes:
      - ./src:/var/www/html:ro
      - ./log/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - laravel

  laravel:
    build:
      context: ./laravel
    image: app-laravel
    container_name: node-app-laravel
    volumes:
      - ./src:/var/www/html:rw
      - ./log/php:/var/log/php:rw
      - ./data:/tmp/data:ro # share during application servers
    restart: always
